version: '3'

services:
  app:
    build:
      context: node
    container_name: node-app
    networks:
      - nodenet
    entrypoint: dockerize -wait tcp://db:3306 -timeout 10000s node index.js
    tty: true
    depends_on:
      - db
      - nginx

  nginx:
    container_name: nginx-node-app
    restart: always
    tty: true
    build:
        context: nginx
    networks:
      - nodenet
    ports:
        - "8080:80"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
    expose:
      - 3306

networks:
  nodenet:
    driver: bridge